### ISSUE TITLE
ignore paths not saved in admin config panel

### ISSUE THREAD

**Issue by phillchill** [getgrav/grav-plugin-sitemap#26]
When I add new paths to the ignores on the admin config panel for the plugin and press 'save', the new path is not saved to the list. I do get a "Successfully saved" notification.

an example of a path I've tried to add:
`/chapters/3-70000-obeti`

Adding the paths manually in `user/config/plugins/sitemap/sitemap.yaml` works.

I'm using OSX Chrome and running latest Grav with Sitemap v1.7.0

**Comment by flaviocopes** [comment]
Replicated. I went back to all Admin plugin changes and after a bit of bisecting I tracked the commit that introduces the problem, it's https://github.com/getgrav/grav-plugin-admin/commit/aba43374dea425d87aea357c750ff3bfdff8c12d 

@w00fz do you have an idea why that might be happening? It's an `array` field:


```
    ignores:
        type: array
        label: Ignore
        help: "URLs to ignore"
        value_only: true
        placeholder_value: /ignore-this-route
```

cannot add new items after this commit. If not I'll try some debugging tomorrow.
