### ISSUE TITLE
Invalid root element, missing trailing slash

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav-plugin-sitemap#87]
See https://github.com/getgrav/grav/issues/3127

Tl;dr: The homepage should be `https://homepage.com/`, but currently is `https://homepage.com`.
This should be fixed in Grav, but the plugin is affected.

**Comment by NicoHood** [comment]
Temporary workaround:
```yaml
# TODO workaround for https://github.com/getgrav/grav-plugin-sitemap/issues/87
ignores:
  - '/'
additions:
  -
    location: /
    lastmod: '2021-01-06'
    changefreq: daily
    priority: 1.0
```
